# Generated by Django 5.2.17 on 2026-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_dob', models.CharField(max_length=50)),
                ('mrn', models.CharField(max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=255)),
                ('drug_name', models.CharField(max_length=255)),
                ('home_meds', models.CharField(blank=True, max_length=500)),
                ('patient_records', models.TextField(blank=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('npi', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
