# Generated by Django 5.2.17 on 2026-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
