# Generated by Django 5.2.17 on 2026-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0002_careplan_prompt_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='reference_material',
            field=models.TextField(blank=True),
        ),
    ]
