# Generated by Django 5.2.17 on 2026-09-19 02:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0003_careplan_reference_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('search_query', models.TextField(blank=True)),
                ('retrieved_chunks', models.JSONField(blank=True, null=True)),
                ('reference_material', models.TextField(blank=True)),
                ('rendered_prompt', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('output_text', models.TextField(blank=True)),
                ('stop_reason', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('parse_succeeded', models.BooleanField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='careplan.careplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
