# Generated by Django 5.2.17 on 2026-09-19 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0004_llmcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('primary_diagnosis', models.CharField(max_length=255)),
                ('text', models.TextField(help_text='One specific, checkable fact the care plan should cover.')),
                ('severity', models.CharField(choices=[('must_have', 'Must have'), ('nice_to_have', 'Nice to have')], default='nice_to_have', max_length=20)),
                ('source', models.CharField(blank=True, help_text="Where this came from, e.g. 'Privigen label — Contraindications'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['drug_name', 'primary_diagnosis', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The atomic claim, as pulled out of the generated content.')),
                ('verdict', models.CharField(choices=[('correct', 'Correct'), ('hallucinated', 'Hallucinated'), ('unverifiable', 'Unverifiable')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='careplan.careplan')),
                ('matched_expected_fact', models.ForeignKey(blank=True, help_text="Set this when the claim correctly covers one of the checklist items — that's what Recall counts.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='careplan.expectedfact')),
            ],
        ),
    ]
