# Generated by Django 5.2.17 on 2026-09-17 21:22

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('loinc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='document_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
